variable "organization" {
  type        = string
  description = "Org prefix (e.g., dccc)"
}

variable "team" {
  type        = string
  description = "Team/app prefix (e.g., sp)"
}

variable "env" {
  type        = string
  description = "Environment (dev, uat, prod)"
}

variable "aws_region" {
  type        = string
  description = "AWS region (e.g., us-gov-west-1)"
}

variable "glue_jobs" {
  description = "Manually defined Glue jobs (if any)"
  type = map(object({
    purpose                = string
    script_location        = string
    role_arn               = string
    glue_version           = optional(string, "5.0")
    max_retries            = optional(number, 0)
    timeout                = optional(number, 60)
    worker_type            = optional(string, "G.1X")
    number_of_workers      = optional(number, 2)
    default_arguments      = optional(map(string), {})
    connections            = optional(list(string), [])
    security_configuration = optional(string)
    tags                   = optional(map(string), {})
  }))
  default = {}
}

variable "glue_jobs_autogen" {
  description = "Autogenerated Glue jobs from CI (do not edit by hand)"
  type = map(object({
    purpose                = string
    script_location        = string
    role_arn               = string
    glue_version           = optional(string, "5.0")
    max_retries            = optional(number, 0)
    timeout                = optional(number, 60)
    worker_type            = optional(string, "G.1X")
    number_of_workers      = optional(number, 2)
    default_arguments      = optional(map(string), {})
    connections            = optional(list(string), [])
    security_configuration = optional(string)
    tags                   = optional(map(string), {})
  }))
  default = {}
}